#!/usr/bin/env python3
"""
Seed 30 days of Daily Challenge QCM into daily_challenge_sets.
Run: python3 deploy/seed_daily_challenges.py

Each day has 5 questions, starts at 8h UTC (= 9h Maroc), 5 minutes total.
Covers: Maths, Physique, Chimie, Informatique, Économie, Droit, Biologie, Histoire...
"""
import json, subprocess
from datetime import date, timedelta

START_DATE = date(2026, 4, 14)   # Jour 1 = demain
SHOW_HOUR  = 8                   # 8h UTC = 9h Maroc (heure normale)
TIME_LIMIT = 300                 # 5 minutes pour 5 questions

challenges = [

  # ── Jour 1 ── Algèbre linéaire ─────────────────────────────────────────────
  [
    { "front": "Une matrice carrée A est inversible si et seulement si :",
      "options": ["son déterminant est nul", "son déterminant est non nul",
                  "sa trace est nulle", "elle est diagonale"],
      "correct_answer": "son déterminant est non nul", "subject": "Algèbre linéaire" },
    { "front": "Le rang d'une matrice nulle de taille n×m est :",
      "options": ["n", "m", "0", "nm"],
      "correct_answer": "0", "subject": "Algèbre linéaire" },
    { "front": "Si A et B sont deux matrices inversibles de même taille, (AB)⁻¹ est égal à :",
      "options": ["A⁻¹B⁻¹", "B⁻¹A⁻¹", "A⁻¹ + B⁻¹", "(A+B)⁻¹"],
      "correct_answer": "B⁻¹A⁻¹", "subject": "Algèbre linéaire" },
    { "front": "La valeur propre d'une matrice identité I_n est :",
      "options": ["0", "n", "1", "-1"],
      "correct_answer": "1", "subject": "Algèbre linéaire" },
    { "front": "Le déterminant d'une matrice triangulaire est égal à :",
      "options": ["la somme des éléments diagonaux", "le produit des éléments diagonaux",
                  "0", "1"],
      "correct_answer": "le produit des éléments diagonaux", "subject": "Algèbre linéaire" },
  ],

  # ── Jour 2 ── Mécanique classique ─────────────────────────────────────────
  [
    { "front": "La deuxième loi de Newton s'écrit :",
      "options": ["F = mv", "F = ma", "F = m/a", "F = a/m"],
      "correct_answer": "F = ma", "subject": "Physique — Mécanique" },
    { "front": "L'unité SI de la force est :",
      "options": ["Pascal", "Joule", "Newton", "Watt"],
      "correct_answer": "Newton", "subject": "Physique — Mécanique" },
    { "front": "Un objet en chute libre (sans frottement) a une accélération d'environ :",
      "options": ["9.8 m/s", "9.8 m/s²", "10 m/s", "0 m/s²"],
      "correct_answer": "9.8 m/s²", "subject": "Physique — Mécanique" },
    { "front": "La quantité de mouvement p est définie par :",
      "options": ["p = mv²", "p = ma", "p = mv", "p = m/v"],
      "correct_answer": "p = mv", "subject": "Physique — Mécanique" },
    { "front": "L'énergie cinétique d'un objet de masse m et de vitesse v est :",
      "options": ["mv", "mv²", "½mv²", "½mv"],
      "correct_answer": "½mv²", "subject": "Physique — Mécanique" },
  ],

  # ── Jour 3 ── Chimie organique ─────────────────────────────────────────────
  [
    { "front": "La formule brute du glucose est :",
      "options": ["C₆H₁₂O₅", "C₆H₁₂O₆", "C₁₂H₂₂O₁₁", "C₆H₆O₆"],
      "correct_answer": "C₆H₁₂O₆", "subject": "Chimie organique" },
    { "front": "Un hydrocarbure avec une double liaison C=C est un :",
      "options": ["alcane", "alcyne", "alcène", "arène"],
      "correct_answer": "alcène", "subject": "Chimie organique" },
    { "front": "Le groupe fonctionnel caractéristique des alcools est :",
      "options": ["-COOH", "-CHO", "-OH", "-NH₂"],
      "correct_answer": "-OH", "subject": "Chimie organique" },
    { "front": "La réaction entre un acide carboxylique et un alcool produit :",
      "options": ["un aldéhyde et de l'eau", "un ester et de l'eau",
                  "une cétone et du CO₂", "une amine et du H₂"],
      "correct_answer": "un ester et de l'eau", "subject": "Chimie organique" },
    { "front": "L'alcane le plus simple (1 carbone) est :",
      "options": ["éthane", "propane", "méthane", "butane"],
      "correct_answer": "méthane", "subject": "Chimie organique" },
  ],

  # ── Jour 4 ── Algorithmique ────────────────────────────────────────────────
  [
    { "front": "La complexité temporelle de la recherche binaire est :",
      "options": ["O(n)", "O(n²)", "O(log n)", "O(1)"],
      "correct_answer": "O(log n)", "subject": "Algorithmique" },
    { "front": "La structure de données de type LIFO (Last In First Out) est :",
      "options": ["File (Queue)", "Pile (Stack)", "Liste chaînée", "Arbre binaire"],
      "correct_answer": "Pile (Stack)", "subject": "Algorithmique" },
    { "front": "Un graphe connexe avec n sommets et n-1 arêtes est :",
      "options": ["un graphe complet", "un cycle", "un arbre", "un graphe biparti"],
      "correct_answer": "un arbre", "subject": "Algorithmique" },
    { "front": "La récursivité est le fait qu'une fonction :",
      "options": ["retourne toujours 0", "s'appelle elle-même",
                  "n'a pas de paramètres", "est définie dans une autre fonction"],
      "correct_answer": "s'appelle elle-même", "subject": "Algorithmique" },
    { "front": "Le tri rapide (QuickSort) a une complexité moyenne de :",
      "options": ["O(n²)", "O(n log n)", "O(log n)", "O(n)"],
      "correct_answer": "O(n log n)", "subject": "Algorithmique" },
  ],

  # ── Jour 5 ── Microéconomie ────────────────────────────────────────────────
  [
    { "front": "Selon la loi de la demande, si le prix d'un bien augmente :",
      "options": ["la demande augmente", "la demande diminue",
                  "la demande reste constante", "l'offre diminue"],
      "correct_answer": "la demande diminue", "subject": "Microéconomie" },
    { "front": "L'utilité marginale d'un bien est généralement :",
      "options": ["croissante", "constante", "décroissante", "nulle"],
      "correct_answer": "décroissante", "subject": "Microéconomie" },
    { "front": "En concurrence parfaite, le prix d'équilibre est égal à :",
      "options": ["le coût total moyen", "le coût marginal", "le coût fixe", "le revenu moyen"],
      "correct_answer": "le coût marginal", "subject": "Microéconomie" },
    { "front": "Un monopoleur fixe son prix de façon à ce que :",
      "options": ["P = CM", "Rm = Cm", "P = Cm", "Rm = P"],
      "correct_answer": "Rm = Cm", "subject": "Microéconomie" },
    { "front": "L'élasticité-prix de la demande d'un bien normal est :",
      "options": ["positive", "nulle", "négative", "infinie"],
      "correct_answer": "négative", "subject": "Microéconomie" },
  ],

  # ── Jour 6 ── Droit constitutionnel marocain ──────────────────────────────
  [
    { "front": "La constitution actuelle du Maroc a été adoptée en :",
      "options": ["1996", "2004", "2011", "2016"],
      "correct_answer": "2011", "subject": "Droit constitutionnel" },
    { "front": "Le Parlement marocain est composé de :",
      "options": ["une chambre", "deux chambres", "trois chambres", "quatre chambres"],
      "correct_answer": "deux chambres", "subject": "Droit constitutionnel" },
    { "front": "Le système de gouvernement du Maroc est :",
      "options": ["une République parlementaire", "une Monarchie absolue",
                  "une Monarchie constitutionnelle", "une République présidentielle"],
      "correct_answer": "une Monarchie constitutionnelle", "subject": "Droit constitutionnel" },
    { "front": "Le nombre de régions administratives du Maroc est :",
      "options": ["9", "10", "12", "16"],
      "correct_answer": "12", "subject": "Droit constitutionnel" },
    { "front": "La Constitution de 2011 reconnaît officiellement la langue :",
      "options": ["française", "espagnole", "amazighe", "anglaise"],
      "correct_answer": "amazighe", "subject": "Droit constitutionnel" },
  ],

  # ── Jour 7 ── Biologie cellulaire ─────────────────────────────────────────
  [
    { "front": "L'organite responsable de la synthèse des protéines est :",
      "options": ["le noyau", "le ribosome", "la mitochondrie", "l'appareil de Golgi"],
      "correct_answer": "le ribosome", "subject": "Biologie cellulaire" },
    { "front": "La mitose produit :",
      "options": ["4 cellules haploïdes", "2 cellules haploïdes",
                  "2 cellules diploïdes identiques", "4 cellules diploïdes"],
      "correct_answer": "2 cellules diploïdes identiques", "subject": "Biologie cellulaire" },
    { "front": "La membrane cellulaire est principalement composée de :",
      "options": ["protéines uniquement", "glucides", "une bicouche lipidique", "ADN"],
      "correct_answer": "une bicouche lipidique", "subject": "Biologie cellulaire" },
    { "front": "L'ATP est la principale molécule de :",
      "options": ["stockage de l'information génétique", "transport de l'oxygène",
                  "transfert d'énergie cellulaire", "synthèse des lipides"],
      "correct_answer": "transfert d'énergie cellulaire", "subject": "Biologie cellulaire" },
    { "front": "Les mitochondries sont le siège de :",
      "options": ["la photosynthèse", "la respiration cellulaire",
                  "la traduction des protéines", "la réplication de l'ADN"],
      "correct_answer": "la respiration cellulaire", "subject": "Biologie cellulaire" },
  ],

  # ── Jour 8 ── Analyse mathématique ────────────────────────────────────────
  [
    { "front": "lim(x→0)  sin(x)/x  est égal à :",
      "options": ["0", "∞", "1", "-1"],
      "correct_answer": "1", "subject": "Analyse" },
    { "front": "La dérivée de e^x est :",
      "options": ["xe^(x-1)", "e^x", "ln(x)", "1/x"],
      "correct_answer": "e^x", "subject": "Analyse" },
    { "front": "La dérivée de ln(x) (pour x > 0) est :",
      "options": ["ln(x)", "e^x", "1/x", "x·ln(x)"],
      "correct_answer": "1/x", "subject": "Analyse" },
    { "front": "∫(1/x)dx est égal à :",
      "options": ["-1/x² + C", "x + C", "ln|x| + C", "e^x + C"],
      "correct_answer": "ln|x| + C", "subject": "Analyse" },
    { "front": "La règle de L'Hôpital s'applique aux formes indéterminées de type :",
      "options": ["0 × ∞ uniquement", "0/0 ou ∞/∞", "∞ - ∞ uniquement", "0⁰"],
      "correct_answer": "0/0 ou ∞/∞", "subject": "Analyse" },
  ],

  # ── Jour 9 ── Électricité ──────────────────────────────────────────────────
  [
    { "front": "La loi d'Ohm s'écrit :",
      "options": ["U = R/I", "U = RI", "I = RU", "R = UI"],
      "correct_answer": "U = RI", "subject": "Physique — Électricité" },
    { "front": "L'unité de résistance électrique est :",
      "options": ["Volt (V)", "Ampère (A)", "Watt (W)", "Ohm (Ω)"],
      "correct_answer": "Ohm (Ω)", "subject": "Physique — Électricité" },
    { "front": "La puissance électrique dissipée est :",
      "options": ["P = U/I", "P = UI", "P = U²I", "P = UI²"],
      "correct_answer": "P = UI", "subject": "Physique — Électricité" },
    { "front": "En association en série, les résistances :",
      "options": ["s'additionnent en inverse", "s'additionnent directement",
                  "restent constantes", "se multiplient"],
      "correct_answer": "s'additionnent directement", "subject": "Physique — Électricité" },
    { "front": "Un condensateur stocke l'énergie sous forme de :",
      "options": ["champ magnétique", "énergie mécanique",
                  "champ électrique", "énergie thermique"],
      "correct_answer": "champ électrique", "subject": "Physique — Électricité" },
  ],

  # ── Jour 10 ── Chimie générale ─────────────────────────────────────────────
  [
    { "front": "Le numéro atomique d'un élément correspond au nombre de :",
      "options": ["neutrons", "protons", "électrons de valence", "nucléons"],
      "correct_answer": "protons", "subject": "Chimie générale" },
    { "front": "La liaison ionique résulte d'un :",
      "options": ["partage d'électrons", "transfert d'électrons",
                  "partage de protons", "transfert de protons"],
      "correct_answer": "transfert d'électrons", "subject": "Chimie générale" },
    { "front": "Le pH d'une solution neutre à 25°C est :",
      "options": ["0", "14", "7", "5"],
      "correct_answer": "7", "subject": "Chimie générale" },
    { "front": "La neutralisation d'un acide par une base produit :",
      "options": ["un oxyde et de l'eau", "un sel et de l'eau",
                  "un alcool et du CO₂", "un ester et du H₂"],
      "correct_answer": "un sel et de l'eau", "subject": "Chimie générale" },
    { "front": "Le nombre d'Avogadro vaut environ :",
      "options": ["6.02 × 10²³", "6.02 × 10²²", "3.14 × 10²³", "1.38 × 10²³"],
      "correct_answer": "6.02 × 10²³", "subject": "Chimie générale" },
  ],

  # ── Jour 11 ── Bases de données ────────────────────────────────────────────
  [
    { "front": "SQL signifie :",
      "options": ["Simple Query Language", "Structured Query Language",
                  "Server Query Logic", "Sequential Query List"],
      "correct_answer": "Structured Query Language", "subject": "Bases de données" },
    { "front": "La clé primaire d'une table sert à :",
      "options": ["chiffrer les données", "identifier de façon unique chaque ligne",
                  "créer un index secondaire", "relier deux bases de données"],
      "correct_answer": "identifier de façon unique chaque ligne", "subject": "Bases de données" },
    { "front": "Un INNER JOIN retourne :",
      "options": ["toutes les lignes de la table gauche",
                  "toutes les lignes de la table droite",
                  "les lignes ayant une correspondance dans les deux tables",
                  "toutes les lignes des deux tables"],
      "correct_answer": "les lignes ayant une correspondance dans les deux tables",
      "subject": "Bases de données" },
    { "front": "La normalisation d'une base de données vise à :",
      "options": ["accélérer les lectures", "éliminer la redondance des données",
                  "chiffrer les données sensibles", "réduire le nombre de tables"],
      "correct_answer": "éliminer la redondance des données", "subject": "Bases de données" },
    { "front": "La commande SQL pour supprimer une table est :",
      "options": ["DELETE TABLE", "REMOVE TABLE", "DROP TABLE", "CLEAR TABLE"],
      "correct_answer": "DROP TABLE", "subject": "Bases de données" },
  ],

  # ── Jour 12 ── Macroéconomie ───────────────────────────────────────────────
  [
    { "front": "Le PIB mesure :",
      "options": ["la valeur des importations uniquement",
                  "la valeur de toute la production réalisée sur le territoire national",
                  "les revenus des citoyens à l'étranger",
                  "les dépenses publiques de l'État"],
      "correct_answer": "la valeur de toute la production réalisée sur le territoire national",
      "subject": "Macroéconomie" },
    { "front": "L'inflation est définie comme :",
      "options": ["une baisse du taux de chômage", "une hausse générale et durable des prix",
                  "une augmentation du PIB", "une dépréciation de la monnaie uniquement"],
      "correct_answer": "une hausse générale et durable des prix", "subject": "Macroéconomie" },
    { "front": "La politique monétaire au Maroc est conduite par :",
      "options": ["le Ministère des Finances", "Bank Al-Maghrib",
                  "la Bourse de Casablanca", "le FMI"],
      "correct_answer": "Bank Al-Maghrib", "subject": "Macroéconomie" },
    { "front": "La courbe de Phillips décrit une relation entre :",
      "options": ["PIB et investissement", "inflation et taux de chômage",
                  "exportations et importations", "épargne et consommation"],
      "correct_answer": "inflation et taux de chômage", "subject": "Macroéconomie" },
    { "front": "Le taux de chômage est calculé comme :",
      "options": ["(inactifs / population totale) × 100",
                  "(chômeurs / population active) × 100",
                  "(chômeurs / population totale) × 100",
                  "(emplois vacants / emplois totaux) × 100"],
      "correct_answer": "(chômeurs / population active) × 100", "subject": "Macroéconomie" },
  ],

  # ── Jour 13 ── Droit civil marocain ───────────────────────────────────────
  [
    { "front": "Le Code de la famille marocain (Moudawana) a été révisé en :",
      "options": ["1993", "1998", "2004", "2011"],
      "correct_answer": "2004", "subject": "Droit civil" },
    { "front": "La capacité juridique complète au Maroc est acquise à l'âge de :",
      "options": ["16 ans", "17 ans", "18 ans", "21 ans"],
      "correct_answer": "18 ans", "subject": "Droit civil" },
    { "front": "Un contrat est valide s'il réunit :",
      "options": ["consentement, capacité, objet licite et cause licite",
                  "consentement et signature notariale uniquement",
                  "capacité et témoins uniquement",
                  "un objet et une contrepartie financière"],
      "correct_answer": "consentement, capacité, objet licite et cause licite",
      "subject": "Droit civil" },
    { "front": "La responsabilité civile délictuelle nécessite :",
      "options": ["un contrat signé entre les parties",
                  "une faute, un dommage et un lien de causalité",
                  "uniquement une faute intentionnelle",
                  "une décision de justice préalable"],
      "correct_answer": "une faute, un dommage et un lien de causalité",
      "subject": "Droit civil" },
    { "front": "Le Dahir des obligations et contrats (DOC) marocain date de :",
      "options": ["1913", "1943", "1956", "1962"],
      "correct_answer": "1913", "subject": "Droit civil" },
  ],

  # ── Jour 14 ── Histoire du Maroc ──────────────────────────────────────────
  [
    { "front": "Le Maroc a obtenu son indépendance de la France le :",
      "options": ["1er janvier 1956", "2 mars 1956", "18 novembre 1955", "7 avril 1956"],
      "correct_answer": "2 mars 1956", "subject": "Histoire du Maroc" },
    { "front": "La Marche Verte a eu lieu en :",
      "options": ["1973", "1974", "1975", "1976"],
      "correct_answer": "1975", "subject": "Histoire du Maroc" },
    { "front": "Le roi Mohammed VI est monté sur le trône en :",
      "options": ["1996", "1997", "1999", "2001"],
      "correct_answer": "1999", "subject": "Histoire du Maroc" },
    { "front": "La ville de Fès a été fondée par :",
      "options": ["Moulay Idriss II", "Youssef Ibn Tachfine",
                  "Abd al-Mumin", "Ahmad al-Mansur"],
      "correct_answer": "Moulay Idriss II", "subject": "Histoire du Maroc" },
    { "front": "La période du Protectorat français au Maroc s'étend de :",
      "options": ["1900 à 1956", "1912 à 1956", "1912 à 1960", "1906 à 1956"],
      "correct_answer": "1912 à 1956", "subject": "Histoire du Maroc" },
  ],

  # ── Jour 15 ── Probabilités ────────────────────────────────────────────────
  [
    { "front": "P(A ∪ B) est égal à :",
      "options": ["P(A) + P(B)", "P(A) × P(B)",
                  "P(A) + P(B) − P(A ∩ B)", "P(A) − P(B)"],
      "correct_answer": "P(A) + P(B) − P(A ∩ B)", "subject": "Probabilités" },
    { "front": "La probabilité de l'événement certain Ω est :",
      "options": ["0", "0.5", "1", "indéfinie"],
      "correct_answer": "1", "subject": "Probabilités" },
    { "front": "Deux événements A et B sont indépendants si :",
      "options": ["P(A ∩ B) = P(A) + P(B)", "P(A ∩ B) = P(A) × P(B)",
                  "P(A ∪ B) = 1", "P(A) = P(B)"],
      "correct_answer": "P(A ∩ B) = P(A) × P(B)", "subject": "Probabilités" },
    { "front": "L'espérance E(aX + b) est égale à :",
      "options": ["aE(X) + b", "E(X) + b", "aE(X)", "a²E(X) + b"],
      "correct_answer": "aE(X) + b", "subject": "Probabilités" },
    { "front": "La loi binomiale B(n, p) modélise :",
      "options": ["le temps d'attente", "le nombre de succès en n essais indépendants",
                  "une variable continue", "la distribution normale"],
      "correct_answer": "le nombre de succès en n essais indépendants",
      "subject": "Probabilités" },
  ],

  # ── Jour 16 ── Optique ────────────────────────────────────────────────────
  [
    { "front": "La vitesse de la lumière dans le vide est d'environ :",
      "options": ["3×10⁶ m/s", "3×10⁸ m/s", "3×10¹⁰ m/s", "3×10⁴ m/s"],
      "correct_answer": "3×10⁸ m/s", "subject": "Physique — Optique" },
    { "front": "L'indice de réfraction n d'un milieu est défini par :",
      "options": ["n = v/c", "n = c/v", "n = c × v", "n = λ/f"],
      "correct_answer": "n = c/v", "subject": "Physique — Optique" },
    { "front": "La loi de Snell-Descartes (réfraction) s'écrit :",
      "options": ["n₁ cos θ₁ = n₂ cos θ₂", "n₁ sin θ₁ = n₂ sin θ₂",
                  "n₁ / sin θ₁ = n₂ / sin θ₂", "n₁ tan θ₁ = n₂ tan θ₂"],
      "correct_answer": "n₁ sin θ₁ = n₂ sin θ₂", "subject": "Physique — Optique" },
    { "front": "Une lentille convergente a une distance focale :",
      "options": ["négative", "nulle", "positive", "infinie"],
      "correct_answer": "positive", "subject": "Physique — Optique" },
    { "front": "La réflexion totale se produit quand l'angle d'incidence est :",
      "options": ["inférieur à l'angle critique", "égal à 0°",
                  "supérieur à l'angle critique", "égal à 90°"],
      "correct_answer": "supérieur à l'angle critique", "subject": "Physique — Optique" },
  ],

  # ── Jour 17 ── Thermodynamique chimique ──────────────────────────────────
  [
    { "front": "L'enthalpie standard de formation d'un élément dans son état standard est :",
      "options": ["1 kJ/mol", "-1 kJ/mol", "0 kJ/mol", "indéfinie"],
      "correct_answer": "0 kJ/mol", "subject": "Thermochimie" },
    { "front": "Une réaction exothermique a une enthalpie de réaction :",
      "options": ["ΔH > 0", "ΔH = 0", "ΔH < 0", "ΔH indéfinie"],
      "correct_answer": "ΔH < 0", "subject": "Thermochimie" },
    { "front": "L'énergie libre de Gibbs G permet de prévoir la spontanéité. Une réaction est spontanée si :",
      "options": ["ΔG > 0", "ΔG = 0", "ΔG < 0", "ΔS < 0"],
      "correct_answer": "ΔG < 0", "subject": "Thermochimie" },
    { "front": "Le 2ᵉ principe de la thermodynamique énonce que l'entropie de l'univers :",
      "options": ["reste constante", "augmente toujours", "diminue toujours",
                  "est nulle à 0 K"],
      "correct_answer": "augmente toujours", "subject": "Thermochimie" },
    { "front": "La relation de Gibbs-Helmholtz est :",
      "options": ["ΔG = ΔH − TΔS", "ΔG = ΔH + TΔS", "ΔG = ΔS − TΔH",
                  "ΔG = ΔH × ΔS"],
      "correct_answer": "ΔG = ΔH − TΔS", "subject": "Thermochimie" },
  ],

  # ── Jour 18 ── Systèmes d'exploitation ───────────────────────────────────
  [
    { "front": "Un système d'exploitation a comme rôle principal de :",
      "options": ["compiler les programmes", "gérer les ressources matérielles et logicielles",
                  "concevoir des interfaces graphiques", "effectuer des calculs numériques"],
      "correct_answer": "gérer les ressources matérielles et logicielles",
      "subject": "Systèmes d'exploitation" },
    { "front": "Un processus est :",
      "options": ["un fichier exécutable", "un programme en cours d'exécution",
                  "une instruction machine", "une partition disque"],
      "correct_answer": "un programme en cours d'exécution",
      "subject": "Systèmes d'exploitation" },
    { "front": "La mémoire virtuelle permet de :",
      "options": ["augmenter la fréquence du CPU", "étendre la RAM en utilisant le disque",
                  "protéger les données par chiffrement", "accélérer le réseau"],
      "correct_answer": "étendre la RAM en utilisant le disque",
      "subject": "Systèmes d'exploitation" },
    { "front": "L'interblocage (deadlock) survient quand :",
      "options": ["un processus boucle indéfiniment",
                  "deux processus attendent chacun une ressource détenue par l'autre",
                  "le CPU est à 100%", "la mémoire est saturée"],
      "correct_answer": "deux processus attendent chacun une ressource détenue par l'autre",
      "subject": "Systèmes d'exploitation" },
    { "front": "Le système de fichiers ext4 est principalement utilisé sous :",
      "options": ["Windows", "macOS", "Linux", "Android uniquement"],
      "correct_answer": "Linux", "subject": "Systèmes d'exploitation" },
  ],

  # ── Jour 19 ── Commerce international ────────────────────────────────────
  [
    { "front": "La théorie de l'avantage comparatif est attribuée à :",
      "options": ["Adam Smith", "John Maynard Keynes", "David Ricardo", "Milton Friedman"],
      "correct_answer": "David Ricardo", "subject": "Commerce international" },
    { "front": "L'OMC (Organisation Mondiale du Commerce) a pour mission de :",
      "options": ["financer le développement", "réguler les échanges commerciaux internationaux",
                  "émettre des monnaies", "contrôler les migrations"],
      "correct_answer": "réguler les échanges commerciaux internationaux",
      "subject": "Commerce international" },
    { "front": "La balance commerciale est définie comme :",
      "options": ["importations − exportations", "exportations − importations",
                  "PIB − consommation", "recettes fiscales − dépenses publiques"],
      "correct_answer": "exportations − importations", "subject": "Commerce international" },
    { "front": "Le dumping consiste à :",
      "options": ["augmenter les droits de douane", "vendre à l'étranger à un prix inférieur au coût de production",
                  "subventionner les exportateurs nationaux",
                  "créer une zone de libre-échange"],
      "correct_answer": "vendre à l'étranger à un prix inférieur au coût de production",
      "subject": "Commerce international" },
    { "front": "Le Maroc est membre de quelle zone de libre-échange régionale ?",
      "options": ["CEDEAO", "Zone de libre-échange continentale africaine (ZLECAf)",
                  "ASEAN", "MERCOSUR"],
      "correct_answer": "Zone de libre-échange continentale africaine (ZLECAf)",
      "subject": "Commerce international" },
  ],

  # ── Jour 20 ── Droit du travail marocain ─────────────────────────────────
  [
    { "front": "La durée légale du travail dans l'industrie au Maroc est de :",
      "options": ["40h/semaine", "44h/semaine", "48h/semaine", "35h/semaine"],
      "correct_answer": "44h/semaine", "subject": "Droit du travail" },
    { "front": "Le Code du travail marocain est la loi n° :",
      "options": ["15-95", "06-99", "65-99", "17-04"],
      "correct_answer": "65-99", "subject": "Droit du travail" },
    { "front": "Un CDI (Contrat à Durée Indéterminée) peut être rompu par :",
      "options": ["l'employeur uniquement", "le salarié uniquement",
                  "l'employeur ou le salarié dans le respect des conditions légales",
                  "uniquement par le tribunal"],
      "correct_answer": "l'employeur ou le salarié dans le respect des conditions légales",
      "subject": "Droit du travail" },
    { "front": "La CNSS (Caisse Nationale de Sécurité Sociale) couvre :",
      "options": ["uniquement les fonctionnaires", "les salariés du secteur privé",
                  "les professions libérales uniquement", "les agriculteurs uniquement"],
      "correct_answer": "les salariés du secteur privé", "subject": "Droit du travail" },
    { "front": "Le salaire minimum interprofessionnel garanti au Maroc est appelé :",
      "options": ["SMIC", "SMIG", "RMG", "SMG"],
      "correct_answer": "SMIG", "subject": "Droit du travail" },
  ],

  # ── Jour 21 ── Génétique ──────────────────────────────────────────────────
  [
    { "front": "L'ADN (acide désoxyribonucléique) est composé de :",
      "options": ["acides aminés", "nucléotides", "acides gras", "monosaccharides"],
      "correct_answer": "nucléotides", "subject": "Génétique" },
    { "front": "La méiose produit :",
      "options": ["2 cellules diploïdes", "4 cellules diploïdes",
                  "4 cellules haploïdes", "2 cellules haploïdes"],
      "correct_answer": "4 cellules haploïdes", "subject": "Génétique" },
    { "front": "Une mutation est :",
      "options": ["un changement du nombre de chromosomes uniquement",
                  "toute modification permanente de la séquence d'ADN",
                  "uniquement un changement d'une seule base",
                  "une variation de l'expression génique sans modification d'ADN"],
      "correct_answer": "toute modification permanente de la séquence d'ADN",
      "subject": "Génétique" },
    { "front": "Selon Mendel, lors de la formation des gamètes, les deux allèles d'un gène :",
      "options": ["restent ensemble", "se séparent (loi de ségrégation)",
                  "fusionnent", "disparaissent"],
      "correct_answer": "se séparent (loi de ségrégation)", "subject": "Génétique" },
    { "front": "L'être humain possède combien de paires de chromosomes ?",
      "options": ["22", "23", "24", "46"],
      "correct_answer": "23", "subject": "Génétique" },
  ],

  # ── Jour 22 ── Géométrie analytique ──────────────────────────────────────
  [
    { "front": "La distance entre deux points A(x₁,y₁) et B(x₂,y₂) est :",
      "options": ["|x₂−x₁| + |y₂−y₁|", "√((x₂−x₁)² + (y₂−y₁)²)",
                  "(x₂−x₁)² + (y₂−y₁)²", "√|x₂−x₁| + √|y₂−y₁|"],
      "correct_answer": "√((x₂−x₁)² + (y₂−y₁)²)", "subject": "Géométrie" },
    { "front": "L'équation d'un cercle de centre (a,b) et de rayon r est :",
      "options": ["(x−a) + (y−b) = r", "(x−a)² + (y−b)² = r",
                  "(x−a)² + (y−b)² = r²", "(x+a)² + (y+b)² = r²"],
      "correct_answer": "(x−a)² + (y−b)² = r²", "subject": "Géométrie" },
    { "front": "La pente d'une droite passant par (x₁,y₁) et (x₂,y₂) est :",
      "options": ["(x₂−x₁)/(y₂−y₁)", "(y₂−y₁)/(x₂−x₁)",
                  "(x₂+x₁)/(y₂+y₁)", "(y₂+y₁)/(x₂+x₁)"],
      "correct_answer": "(y₂−y₁)/(x₂−x₁)", "subject": "Géométrie" },
    { "front": "La parabole y = ax² + bx + c s'ouvre vers le haut quand :",
      "options": ["b > 0", "c > 0", "a > 0", "a < 0"],
      "correct_answer": "a > 0", "subject": "Géométrie" },
    { "front": "Deux droites sont perpendiculaires si le produit de leurs pentes est :",
      "options": ["0", "1", "−1", "indéfini"],
      "correct_answer": "−1", "subject": "Géométrie" },
  ],

  # ── Jour 23 ── Thermodynamique physique ──────────────────────────────────
  [
    { "front": "Le premier principe de la thermodynamique s'énonce :",
      "options": ["l'entropie de l'univers augmente", "l'énergie interne est conservée (ΔU = W + Q)",
                  "la température absolue ne peut être négative",
                  "tout système tend vers un équilibre"],
      "correct_answer": "l'énergie interne est conservée (ΔU = W + Q)",
      "subject": "Thermodynamique" },
    { "front": "Le zéro absolu (0 K) correspond à :",
      "options": ["-100°C", "-273.15°C", "-373.15°C", "0°C"],
      "correct_answer": "-273.15°C", "subject": "Thermodynamique" },
    { "front": "La chaleur spécifique de l'eau est d'environ :",
      "options": ["1000 J/(kg·K)", "2093 J/(kg·K)", "4186 J/(kg·K)", "500 J/(kg·K)"],
      "correct_answer": "4186 J/(kg·K)", "subject": "Thermodynamique" },
    { "front": "Le rendement maximal théorique d'un moteur thermique (Carnot) est :",
      "options": ["η = 1 − Tf/Tc", "η = 1 + Tf/Tc", "η = Tc/Tf", "η = 1"],
      "correct_answer": "η = 1 − Tf/Tc", "subject": "Thermodynamique" },
    { "front": "La conduction thermique est décrite par la loi de :",
      "options": ["Newton", "Fourier", "Boyle", "Gay-Lussac"],
      "correct_answer": "Fourier", "subject": "Thermodynamique" },
  ],

  # ── Jour 24 ── Cinétique chimique ─────────────────────────────────────────
  [
    { "front": "La vitesse d'une réaction chimique est généralement exprimée comme :",
      "options": ["la variation de température / temps",
                  "la variation de concentration / temps",
                  "la variation de pression / température",
                  "la variation de masse / volume"],
      "correct_answer": "la variation de concentration / temps",
      "subject": "Cinétique chimique" },
    { "front": "Un catalyseur agit en :",
      "options": ["augmentant l'énergie d'activation",
                  "diminuant l'énergie d'activation sans être consommé",
                  "étant consommé pendant la réaction",
                  "augmentant la température du système"],
      "correct_answer": "diminuant l'énergie d'activation sans être consommé",
      "subject": "Cinétique chimique" },
    { "front": "La loi d'Arrhenius exprime la dépendance de la constante de vitesse k à :",
      "options": ["la concentration des réactifs", "la température",
                  "la pression uniquement", "le volume du réacteur"],
      "correct_answer": "la température", "subject": "Cinétique chimique" },
    { "front": "Le temps de demi-vie t₁/₂ est le temps pour que la concentration de A :",
      "options": ["devienne nulle", "soit divisée par 4",
                  "soit divisée par 2", "double"],
      "correct_answer": "soit divisée par 2", "subject": "Cinétique chimique" },
    { "front": "Pour une réaction d'ordre 0, la vitesse est :",
      "options": ["proportionnelle à [A]", "proportionnelle à [A]²",
                  "constante (indépendante de [A])", "inversement proportionnelle à [A]"],
      "correct_answer": "constante (indépendante de [A])",
      "subject": "Cinétique chimique" },
  ],

  # ── Jour 25 ── Programmation orientée objet ───────────────────────────────
  [
    { "front": "L'encapsulation en POO consiste à :",
      "options": ["hériter des attributs d'une classe parente",
                  "protéger les données internes d'une classe en les rendant privées",
                  "créer plusieurs méthodes avec le même nom",
                  "définir une classe abstraite"],
      "correct_answer": "protéger les données internes d'une classe en les rendant privées",
      "subject": "POO" },
    { "front": "L'héritage en POO signifie qu'une classe enfant :",
      "options": ["remplace la classe parente", "hérite des attributs et méthodes de la classe parente",
                  "est indépendante de la classe parente",
                  "copie le code de la classe parente"],
      "correct_answer": "hérite des attributs et méthodes de la classe parente",
      "subject": "POO" },
    { "front": "Le polymorphisme permet à :",
      "options": ["une classe d'avoir plusieurs constructeurs",
                  "une méthode d'avoir le même comportement dans toutes les classes",
                  "différentes classes de répondre différemment à la même interface",
                  "un objet de changer de type dynamiquement"],
      "correct_answer": "différentes classes de répondre différemment à la même interface",
      "subject": "POO" },
    { "front": "Une interface en POO est :",
      "options": ["une classe avec implémentation complète",
                  "un contrat définissant des méthodes sans implémentation",
                  "une classe abstraite avec attributs",
                  "une méthode statique"],
      "correct_answer": "un contrat définissant des méthodes sans implémentation",
      "subject": "POO" },
    { "front": "Le constructeur d'une classe est appelé :",
      "options": ["à chaque accès à un attribut",
                  "lors de la destruction de l'objet",
                  "lors de la création d'un nouvel objet",
                  "une seule fois au démarrage du programme"],
      "correct_answer": "lors de la création d'un nouvel objet", "subject": "POO" },
  ],

  # ── Jour 26 ── Finance d'entreprise ──────────────────────────────────────
  [
    { "front": "La VAN (Valeur Actuelle Nette) d'un projet est positive signifie que :",
      "options": ["le projet génère une perte", "le projet est rentable (crée de la valeur)",
                  "le TRI est nul", "le projet ne présente aucun risque"],
      "correct_answer": "le projet est rentable (crée de la valeur)",
      "subject": "Finance d'entreprise" },
    { "front": "Le TRI (Taux de Rentabilité Interne) est le taux qui :",
      "options": ["maximise la VAN", "annule la VAN",
                  "maximise les flux de trésorerie", "minimise le coût du capital"],
      "correct_answer": "annule la VAN", "subject": "Finance d'entreprise" },
    { "front": "L'effet de levier financier amplifie :",
      "options": ["uniquement les pertes", "uniquement les gains",
                  "à la fois les gains et les pertes", "aucun des deux"],
      "correct_answer": "à la fois les gains et les pertes",
      "subject": "Finance d'entreprise" },
    { "front": "Dans un bilan comptable, on a toujours :",
      "options": ["Actif > Passif", "Actif = Passif + Capitaux propres",
                  "Actif = Passif − Capitaux propres",
                  "Capitaux propres = Passif"],
      "correct_answer": "Actif = Passif + Capitaux propres",
      "subject": "Finance d'entreprise" },
    { "front": "L'EBITDA signifie résultat avant déduction :",
      "options": ["des impôts et taxes uniquement",
                  "des intérêts, impôts, amortissements et provisions",
                  "des salaires et charges sociales",
                  "du coût des marchandises vendues"],
      "correct_answer": "des intérêts, impôts, amortissements et provisions",
      "subject": "Finance d'entreprise" },
  ],

  # ── Jour 27 ── Droit administratif ───────────────────────────────────────
  [
    { "front": "Le principe de légalité en droit administratif signifie que :",
      "options": ["les citoyens doivent respecter la loi",
                  "l'administration est soumise au droit",
                  "les tribunaux sont indépendants",
                  "la loi est supérieure à la constitution"],
      "correct_answer": "l'administration est soumise au droit",
      "subject": "Droit administratif" },
    { "front": "Un recours pour excès de pouvoir vise à :",
      "options": ["obtenir des dommages et intérêts",
                  "annuler un acte administratif illégal",
                  "interpréter un texte législatif",
                  "contraindre l'administration à agir"],
      "correct_answer": "annuler un acte administratif illégal",
      "subject": "Droit administratif" },
    { "front": "Le service public est caractérisé par :",
      "options": ["la recherche du profit", "l'activité d'intérêt général sous contrôle public",
                  "l'absence de règlement", "son caractère exclusivement privé"],
      "correct_answer": "l'activité d'intérêt général sous contrôle public",
      "subject": "Droit administratif" },
    { "front": "Au Maroc, le tribunal administratif est compétent pour :",
      "options": ["les litiges entre particuliers uniquement",
                  "les litiges entre l'administration et les administrés",
                  "les infractions pénales", "les litiges commerciaux"],
      "correct_answer": "les litiges entre l'administration et les administrés",
      "subject": "Droit administratif" },
    { "front": "Un acte administratif unilatéral est :",
      "options": ["un contrat entre deux administrations",
                  "une décision prise par l'administration sans accord du destinataire",
                  "une loi votée par le Parlement",
                  "un jugement du tribunal administratif"],
      "correct_answer": "une décision prise par l'administration sans accord du destinataire",
      "subject": "Droit administratif" },
  ],

  # ── Jour 28 ── Microbiologie ──────────────────────────────────────────────
  [
    { "front": "Les bactéries sont des cellules :",
      "options": ["eucaryotes avec noyau", "procaryotes sans noyau membranaire",
                  "eucaryotes sans mitochondries", "procaryotes avec noyau"],
      "correct_answer": "procaryotes sans noyau membranaire", "subject": "Microbiologie" },
    { "front": "Les virus sont des parasites :",
      "options": ["extracellulaires facultatifs", "intracellulaires obligatoires",
                  "capables de se reproduire seuls", "de taille supérieure aux bactéries"],
      "correct_answer": "intracellulaires obligatoires", "subject": "Microbiologie" },
    { "front": "Alexander Fleming a découvert la pénicilline en :",
      "options": ["1905", "1918", "1928", "1945"],
      "correct_answer": "1928", "subject": "Microbiologie" },
    { "front": "La stérilisation consiste à :",
      "options": ["réduire la charge microbienne de 99%",
                  "éliminer tous les micro-organismes y compris les spores",
                  "éliminer uniquement les bactéries pathogènes",
                  "inhiber la croissance bactérienne sans tuer"],
      "correct_answer": "éliminer tous les micro-organismes y compris les spores",
      "subject": "Microbiologie" },
    { "front": "La coloration de Gram distingue les bactéries gram+ qui ont :",
      "options": ["une membrane externe lipopolysaccharidique",
                  "une paroi épaisse de peptidoglycane",
                  "aucune paroi cellulaire",
                  "une capsule externe de polysaccharides"],
      "correct_answer": "une paroi épaisse de peptidoglycane", "subject": "Microbiologie" },
  ],

  # ── Jour 29 ── Statistiques appliquées ───────────────────────────────────
  [
    { "front": "La moyenne arithmétique d'une série de valeurs est :",
      "options": ["la valeur la plus fréquente", "la valeur centrale après tri",
                  "la somme des valeurs divisée par leur nombre",
                  "la racine carrée de la variance"],
      "correct_answer": "la somme des valeurs divisée par leur nombre",
      "subject": "Statistiques" },
    { "front": "La médiane est :",
      "options": ["la valeur la plus fréquente dans la série",
                  "la valeur qui divise la distribution en deux parties égales",
                  "la somme des valeurs / n",
                  "la différence entre le maximum et le minimum"],
      "correct_answer": "la valeur qui divise la distribution en deux parties égales",
      "subject": "Statistiques" },
    { "front": "L'écart-type est :",
      "options": ["la variance au carré", "la racine carrée de la variance",
                  "la variance divisée par n", "la moyenne des déviations absolues"],
      "correct_answer": "la racine carrée de la variance", "subject": "Statistiques" },
    { "front": "Le coefficient de corrélation de Pearson r prend des valeurs :",
      "options": ["entre 0 et 1", "entre −∞ et +∞",
                  "entre −1 et +1", "entre 0 et +∞"],
      "correct_answer": "entre −1 et +1", "subject": "Statistiques" },
    { "front": "Un histogramme représente :",
      "options": ["la relation entre deux variables",
                  "la distribution d'une variable quantitative continue",
                  "l'évolution d'une variable dans le temps",
                  "la comparaison de plusieurs catégories"],
      "correct_answer": "la distribution d'une variable quantitative continue",
      "subject": "Statistiques" },
  ],

  # ── Jour 30 ── Culture générale — Le Maroc ───────────────────────────────
  [
    { "front": "La capitale du Maroc est :",
      "options": ["Casablanca", "Fès", "Rabat", "Marrakech"],
      "correct_answer": "Rabat", "subject": "Culture générale" },
    { "front": "La monnaie officielle du Maroc est :",
      "options": ["Dinar", "Franc marocain", "Dirham (MAD)", "Riyal"],
      "correct_answer": "Dirham (MAD)", "subject": "Culture générale" },
    { "front": "Depuis la Constitution de 2011, les langues officielles du Maroc sont :",
      "options": ["l'arabe uniquement", "l'arabe et le français",
                  "l'arabe et l'amazighe", "l'arabe, l'amazighe et le français"],
      "correct_answer": "l'arabe et l'amazighe", "subject": "Culture générale" },
    { "front": "La plus haute montagne du Maroc est le Jbel Toubkal qui culmine à :",
      "options": ["3 500 m", "3 850 m", "4 167 m", "4 500 m"],
      "correct_answer": "4 167 m", "subject": "Culture générale" },
    { "front": "La Fête du Trône au Maroc est célébrée chaque année le :",
      "options": ["18 novembre", "2 mars", "30 juillet", "14 août"],
      "correct_answer": "30 juillet", "subject": "Culture générale" },
  ],

]  # fin challenges

# ─── Génération du SQL ───────────────────────────────────────────────────────
lines = []
for i, questions in enumerate(challenges):
    d = START_DATE + timedelta(days=i)
    qs_json = json.dumps(questions, ensure_ascii=False).replace("'", "''")
    lines.append(
        f"INSERT INTO daily_challenge_sets "
        f"(challenge_date, faculty, show_from_hour, time_limit_s, questions, is_active) "
        f"VALUES ('{d}', 'all', {SHOW_HOUR}, {TIME_LIMIT}, '{qs_json}'::jsonb, TRUE) "
        f"ON CONFLICT (challenge_date, faculty) DO UPDATE SET "
        f"questions = EXCLUDED.questions, "
        f"time_limit_s = EXCLUDED.time_limit_s, "
        f"show_from_hour = EXCLUDED.show_from_hour, "
        f"is_active = EXCLUDED.is_active, "
        f"updated_at = NOW();"
    )

sql = '\n'.join(lines)
with open('/tmp/seed_30days.sql', 'w', encoding='utf-8') as f:
    f.write(sql)

print(f"✓ Fichier SQL généré : {len(lines)} jours, {len(lines)*5} questions")

# ─── Upload + exécution sur le serveur ──────────────────────────────────────
SSH_KEY = "~/.ssh/tawjeeh_deploy"
SERVER  = "root@5.189.153.144"
DB_PASS = "db48fb0ef5014ce5b53fb196dc4c0c20"

print("⬆  Upload vers le serveur…")
subprocess.run(
    ["scp", "-i", SSH_KEY, "/tmp/seed_30days.sql", f"{SERVER}:/tmp/seed_30days.sql"],
    check=True
)

print("▶  Exécution du SQL sur la base de données…")
result = subprocess.run(
    ["ssh", "-i", SSH_KEY, SERVER,
     f"PGPASSWORD='{DB_PASS}' psql -h localhost -U tawjeeh -d tawjeeh -f /tmp/seed_30days.sql"],
    capture_output=True, text=True
)
print(result.stdout)
if result.returncode != 0:
    print("ERREUR :", result.stderr)
else:
    print(f"✅ {len(lines)} défis quotidiens insérés/mis à jour avec succès !")
